### ISSUE TITLE
Getting ActionController::InvalidAuthenticityToken exception when signing in

### ISSUE THREAD

**Issue by bennyzr** [lowjoel/activerecord-userstamp#16]
Hi,

I'm using Rails 5.0.0.1 and Devise 4.2.0 and am getting a ActionController::InvalidAuthenticityToken exception only when signing in. If I remove the gem, sign in, add the gem and restart the server I don't get any exception when requesting pages.  The handle_unverified_request method is being called right before the exception is raised.

Please help.

**Comment by lowjoel** [comment]
Do you have a minimal sample project that demonstrates this?

**Comment by bennyzr** [comment]
I just pushed a brand new project https://github.com/bennyzr/rails-devise-pundit using the template https://github.com/RailsApps/rails-devise-pundit. I am seeing the same error when trying to login.

**Comment by bennyzr** [comment]
It seems like a new session object is being created when logging-in which doesn't match-up with the client's CSRF token.

**Comment by lowjoel** [comment]
@bennyzr I've added one commit at https://github.com/lowjoel/rails-devise-pundit to make the application work (I was getting pundit errors, and missing the sign in/out nav links)... and I don't get any problems signing in or out.

**Comment by bennyzr** [comment]
I cloned your version and tested it. When clicking on the "sign in" link and entering user@example.com with the password "changeme" you will not get authenticated and you will see "Can't verify CSRF token authenticity." in the log. Try clicking on the Users link and you will get a 401 and be re-directed to the login page. If you add the with: exception option to the protect_from_forgery directive in the ApplicationController file you will see the exception I am referring to.

**Comment by lowjoel** [comment]
@bennyzr: this was added into the Devise readme: https://github.com/plataformatec/devise/pull/4033/files

use `protect_from_forgery with: :exception, prepend: true`

That worked for me, please reopen this if it does not solve your problem.
